# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, staging ]
    paths: 'config/d1/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  buildstaging:
    if: endsWith('staging', github.ref)
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: echo "Build staging for config d1"

  buildprod:
    if: endsWith('main', github.ref)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: sync
        run: echo "Sync staging to prod"
