# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, staging ]
    paths: 'config/d1/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  show:
    runs-on: ubuntu-latest
    steps:
      - name: show
        env:
          GHREF: ${{ github.ref }}
          GHHREF: ${{ github.href }}
        run: |
          echo $GHREF $GHHREF
    

  buildstaging:
    if: endsWith(github.ref, 'staging')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          echo "Build staging for config d1"
          echo "yarn build etc."
    
      # - name: config_aws_creds_staging
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id:
      #     aws-secret-access-key:
      #     aws-region: us-east-1

      - name: sync_build_s3
        run: |
          echo aws s3 sync 
          echo aws cloudformation create-invalidation 

  buildprod:
    if: endsWith(github.ref, 'main')
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: sync
        run: echo "Sync staging to prod"

      # - name: config_aws_creds_staging
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id:
      #     aws-secret-access-key:
      #     aws-region: us-east-1

      - name: sync_build_s3
        run: |
          echo aws s3 sync staging_bucket prod_bucket
          echo aws cloudformation create-invalidation 
